### PR TITLE
Heat plugin needed to cluster devices

### LINKED ISSUE #61: Heat plugin needed to cluster devices
A heat plugin resource is needed to allow clustering of an active/standby group. This will use the f5-sdk f5/multi_device/cluster resources and create a clustered group of devices.

### PR DESCRIPTION
**Pull request by pjbreaux**
@szakeri 

Issues:
Fixes #61

Problem:
A heat plugin resource is needed to allow clustering of an
active/standby group. This will use the f5-sdk f5/multi_device/cluster
resources and create a clustered group of devices.

Analysis:
Utilize the ClusterManager from the f5-sdk to cluster devices. For now
the only supported number are 2 devices in an active/standby cluster.
The plugin allows only creation/deletion. This may change in the future.

Tests:
All plugins and their tests have been refactored to use the
ManagementRoot resource from f5-sdk instead of f5.bigip.BigIP. All tests
pass. We may need to examine dependency relationships since the unit
tests require whatever is needed to run tests on the heat engine.

### CODE REVIEW

**Comment by pjbreaux** [comment]
A great deal of small changes below to refactor the plugins to use ManagementRoot. Also, I have included functional and unit tests for the f5_cm_cluster plugin.

We'll see if the build passes. I was having dependency issues with f5-openstack-test client that it installs compared to what the Heat engine needs.

**Comment by pjbreaux** [comment]
Actually, we cannot merge this until the clustering stuff gets merged into 0.1 in f5-sdk.

**Comment by pjbreaux** [comment]
Need to fix up the plugins since the interface for the sdk has changed. Will push new update.

**Comment by szakeri** [comment]
Functional test failure : 
f5_bigip_device/test_bigip_device.py::test_create_failed_bad_ip FAILED

E       assert 'Failed to establish a new connection' in '{"explanation": "The server has either erred or is incapable of performing the requested operation.", "code": 500, "e...aborted.\', error(111, \'ECONNREFUSED\'))", "traceback": null, "type": "Exception"}, "title": "Internal Server Error"}'
E        +  where '{"explanation": "The server has either erred or is incapable of performing the requested operation.", "code": 500, "e...aborted.\', error(111, \'ECONNREFUSED\'))", "traceback": null, "type": "Exception"}, "title": "Internal Server Error"}' = HTTPInternalServerError().message
E        +    where HTTPInternalServerError() = <ExceptionInfo HTTPInternalServerError tblen=8>.value

**Comment by pjbreaux** [comment]
Ok thanks for your help debugging this. It looks like your version of the Heat engine 2015.1.2 kicks back a different exception message to the Heat client than my heat engine (version 2015.1.3). Although it pains me, I'm going to make the test a little more generic. Forthcoming!

**Comment by pjbreaux** [comment]
Strike that! Not making the test more generic. I'm going to have it conditionally check for these messages and leave a note about the engine versions in the test text in case anyone is curious.

**Pull request merged**
